line-length = 120

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "N",  # PEP8 naming convetions
    "D",  # pydocstyle
]
ignore = [
    "C901", # too complex
    "D100",
    "D103",
    "D104",
    "D401", # imperative mood
    "W191", # indentation contains tabs
]

[lint.pydocstyle]
convention = "google"

[lint.isort]
combine-as-imports = true
