name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.5"  # Pin to a specific version for reproducibility
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml
          uv.lock

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"  # Use Python version from requires-python

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Lint with ruff
      run: uvx ruff check

    - name: Build package
      run: uv build
